version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    command: "sleep infinity"
    network_mode: service:mysql
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ../..:/workspaces:cached

  mysql:
    image: mysql:8.0
    container_name: foodfrenzy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodfrenzy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: